- name: disable NFS3 version
  ansible.builtin.shell: systemctl mask --now rpc-statd.service rpcbind.service rpcbind.socket
  when: nfs_version == 4

- name: start rpcbind
  ansible.builtin.systemd_service:
    name: rpcbind
    state: started
    enabled: true
  when: nfs_version == 3

- name: create NFS server config
  ansible.builtin.template:
    src: nfs.conf
    dest: /etc/nfs.conf

- name: start NFS server
  ansible.builtin.systemd_service:
    name: nfs-server
    state: started
    enabled: true

- name: create exports config
  ansible.builtin.template:
    src: exports
    dest: /etc/exports
  notify: reread exports