- set_fact:
    full_package_list: "{{ debian_packages_list + package_list }}"
  when: 
    - package_list is defined 
    - ansible_facts['os_family']|lower == 'debian'

- set_fact:
    full_package_list: "{{ full_package_list + nfs3_packages }}"
  when: nfs_version == 3

- name: debian installation
  ansible.builtin.debug:
    msg: "It will be debian section in the distant future"