- set_fact:
    full_packages_list: "{{ rhel_packages_list + packages_list|default([]) }}"

- set_fact:
    full_packages_list: "{{ full_packages_list + nfs3_packages }}"
  when: nfs_version == 3

- name: Install/Delete NFS server
  ansible.builtin.yum:
    name: "{{ full_packages_list }}"
    state: "{{ state }}"
    update_cache: yes
    validate_certs: no