- set_fact:
    full_package_list: "{{ rhel_packages_list + package_list }}"
  when: 
    - package_list is defined 
    - ansible_facts['os_family']|lower == 'redhat'

- set_fact:
    full_package_list: "{{ debian_packages_list + package_list }}"
  when: 
    - package_list is defined 
    - ansible_facts['os_family']|lower == 'debian'

- set_fact:
    full_package_list: "{{ full_package_list + nfs3_packages }}"
  when: nfs_version == 3

- name: Install nfs server
  ansible.builtin.yum:
    name: "{{ full_packages_list }}"
    state: "{{ state }}"
    update_cache: yes
    validate_certs: no