- name: stop nfs server
  ansible.builtin.systemd_service:
    name: nfs-server
    state: stopped

- name: stop rpcbind
  ansible.builtin.systemd_service:
    name: rpcbind
    state: stopped
  when: nfs_version == 3

- name: delete nfs server config
  ansible.builtin.file:  
    path: /etc/exports
    state: absent
